export interface Store {
  id: string;
  name: string;
  address: string;
  city: string;
  state: string;
  postalCode?: string;
  country?: string;
  phone?: string;
  website?: string;
  email?: string;
  logoUrl?: string;
  notes?: string;
  priority?: string;
  visible?: string;
}

// Sample store data from CSV - this would normally be parsed from the CSV file
// For Mapbox integration, you'll need to add latitude/longitude coordinates
export const STORES: Store[] = [
  { id: "loc_9yenvvny", name: "Milam's Market - Pinecrest Plaza", address: "11701 S. Dixie Hwy", city: "Miami", state: "FL" },
  { id: "loc_qxjrwwry", name: "Milam's Market- Miami Springs", address: "80 Curtiss Parkway", city: "Miami", state: "FL" },
  { id: "loc_7vny77yq", name: "Milam's Market - Coconut Grove", address: "2969 SW 32nd Ave.", city: "Miami", state: "FL" },
  { id: "loc_xgwrkvj6", name: "Wegmans", address: "5028 West Ridge Road", city: "Erie", state: "PA", postalCode: "16506" },
  { id: "loc_v5yeggem", name: "Milam's Market - Sunny Isles Beach", address: "17100 Collins Ave #119", city: "North Miami Beach", state: "FL" },
  { id: "loc_z72e8y5w", name: "Wegmans", address: "6143 Peach Street", city: "Erie", state: "PA", postalCode: "16509" },
  { id: "loc_kkye77nq", name: "MALS FRESH PRODUCE", address: "312 old cheat road", city: "Morgantown", state: "WV" },
  { id: "loc_qxjrwnvy", name: "Wegmans", address: "945 Fairmount Avenue", city: "Jamestown", state: "NY", postalCode: "14701" },
  { id: "loc_6jwq62m5", name: "Wegmans", address: "1810 Fordham Boulevard", city: "Chapel Hill", state: "NC", postalCode: "27514" },
  { id: "loc_ywnekqgv", name: "Wegmans", address: "1577 Military Road", city: "Niagara Falls", state: "NY", postalCode: "14304" },
  { id: "loc_7vny7emq", name: "Wegmans", address: "601 Amherst Street", city: "Buffalo", state: "NY", postalCode: "14207" },
  { id: "loc_kkye79pq", name: "Wegmans", address: "3710 Davis Drive", city: "Morrisville/West Cary", state: "NC", postalCode: "27560" },
  { id: "loc_p7erpwvk", name: "Wegmans", address: "3135 Niagara Falls Boulevard", city: "Amherst", state: "NY", postalCode: "14228" },
  { id: "loc_8g2p9j76", name: "Wegmans", address: "675 Alberta Drive", city: "Amherst", state: "NY", postalCode: "14226" },
  { id: "loc_qxjrwnqy", name: "Wegmans", address: "3740 McKinley Parkway", city: "Buffalo", state: "NY", postalCode: "14219" },
  { id: "loc_2nvz6y29", name: "Wegmans", address: "370 Orchard Park Road", city: "West Seneca", state: "NY", postalCode: "14224" },
  { id: "loc_wgpx59ex", name: "Wegmans", address: "5275 Sheridan Dr", city: "Williamsville", state: "NY", postalCode: "14221" },
  { id: "loc_9yenvgzy", name: "Wegmans", address: "651 Dick Road", city: "Depew", state: "NY", postalCode: "14043" },
  { id: "loc_v5yeg78m", name: "Wegmans", address: "4960 Transit Road (Losson Rd)", city: "Depew", state: "NY", postalCode: "14043" },
  { id: "loc_nxn2qy75", name: "Wegmans", address: "8270 Transit Road", city: "Buffalo", state: "NY", postalCode: "14221" },
  { id: "loc_z72e8ykw", name: "Wegmans", address: "1200 Wake Towne Drive", city: "Raleigh", state: "NC", postalCode: "27609" },
  { id: "loc_rx8rn27q", name: "Wegmans", address: "11051 Ligon Mill Road", city: "Wake Forest", state: "NC", postalCode: "27587" },
  { id: "loc_jz8257pe", name: "Wegmans", address: "6660 4th Section Rd", city: "Brockport", state: "NY", postalCode: "14420" },
  { id: "loc_rx8rn2yq", name: "Wegmans", address: "345 Colonnade Boulevard", city: "State College", state: "PA", postalCode: "16803" },
  { id: "loc_6jwq6285", name: "Wegmans", address: "4287 Genesee Valley Plaza Rd", city: "Geneseo", state: "NY", postalCode: "14454" },
  { id: "loc_mgwzvq2v", name: "Wegmans", address: "3175 Chili Avenue", city: "Rochester", state: "NY", postalCode: "14624" },
  { id: "loc_jz8257ve", name: "Wegmans", address: "2833 Ridge Road West", city: "Rochester", state: "NY", postalCode: "14626" },
  { id: "loc_9yenvg9y", name: "Wegmans", address: "3177 Latta Road", city: "Rochester", state: "NY", postalCode: "14612" },
  { id: "loc_v5yeg7xm", name: "Wegmans", address: "2301 Lyell Avenue", city: "Rochester", state: "NY", postalCode: "14606" },
  { id: "loc_gp7xemr7", name: "Wegmans", address: "1000 Highway 36 North", city: "Hornell", state: "NY", postalCode: "14843" },
  { id: "loc_ywnekq9v", name: "Wegmans", address: "3701 Mt Read Boulevard", city: "Rochester", state: "NY", postalCode: "14616" },
  { id: "loc_qxjrwney", name: "Wegmans", address: "650 Hylan Drive", city: "Rochester", state: "NY", postalCode: "14609" },
  { id: "loc_gp7xemv7", name: "Wegmans", address: "745 Calkins Road", city: "Rochester", state: "NY", postalCode: "14623" },
  { id: "loc_7vny7e8q", name: "Wegmans", address: "525 Titus Avenue", city: "Rochester", state: "NY", postalCode: "14617" },
  { id: "loc_eqe8nkmv", name: "Wegmans", address: "2200 East Ridge Road", city: "Rochester", state: "NY", postalCode: "14622" },
  { id: "loc_z72e8yww", name: "Wegmans", address: "1750 East Avenue", city: "Rochester", state: "NY", postalCode: "14610" },
  { id: "loc_2nvz6yj9", name: "Wegmans", address: "3195 Monroe Avenue", city: "Pittsford", state: "NY", postalCode: "14618" },
  { id: "loc_xgwrkvy6", name: "Wegmans", address: "1955 Empire Boulevard", city: "Webster", state: "NY", postalCode: "14580" },
  { id: "loc_kkye79wq", name: "Wegmans", address: "851 Fairport Road", city: "East Rochester", state: "NY", postalCode: "14445" },
  { id: "loc_nxn2qyw5", name: "Wegmans", address: "6600 Pittsford-Palmyra Road (Route 31)", city: "Fairport/Perinton", state: "NY" },
  { id: "loc_8g2p9jk6", name: "Wegmans", address: "900 Holt Road", city: "Webster", state: "NY", postalCode: "14580" },
  { id: "loc_wgpx59zx", name: "Wegmans", address: "2157 Penfield Road", city: "Penfield", state: "NY", postalCode: "14526" },
  { id: "loc_ywnekqxv", name: "Wegmans", address: "45131 Columbia Place", city: "Sterling", state: "VA", postalCode: "20166" },
  { id: "loc_p7erpwzk", name: "Wegmans", address: "7830 Wormans Mill Road", city: "Frederick", state: "MD", postalCode: "21701" },
  { id: "loc_qxjrww9y", name: "Wegmans", address: "11620 Monument Drive", city: "Fairfax", state: "VA", postalCode: "22030" },
  { id: "loc_wgpx59jx", name: "Wegmans", address: "20600 Seneca Meadows Parkway", city: "Germantown", state: "MD", postalCode: "20876" },
  { id: "loc_5zpv6n5n", name: "Wegmans", address: "345 Eastern Boulevard", city: "Canandaigua", state: "NY", postalCode: "14424" },
  { id: "loc_eqe8nk5v", name: "Wegmans", address: "1590 Rockville Pike", city: "Rockville", state: "MD", postalCode: "20852" },
  { id: "loc_p7erpw2k", name: "Wegmans", address: "800 West Miller Street", city: "Newark", state: "NY", postalCode: "14513" },
  { id: "loc_eqe8nkrv", name: "Wegmans", address: "24 S Bridge Street", city: "Corning", state: "NY", postalCode: "14830" },
  { id: "loc_kkye79rq", name: "Wegmans", address: "6416 Carlisle Pike", city: "Mechanicsburg", state: "PA", postalCode: "17050" },
  { id: "loc_7vny7ekq", name: "Wegmans", address: "201 William Street", city: "Williamsport", state: "PA", postalCode: "17701" },
  { id: "loc_rx8rn2mq", name: "Wegmans", address: "300 Hamilton Street", city: "Geneva", state: "NY", postalCode: "14456" },
  { id: "loc_jz8257re", name: "Wegmans", address: "1100 Clemens Center Parkway", city: "Elmira", state: "NY", postalCode: "14901" },
  { id: "loc_2nvz6yp9", name: "Wegmans", address: "10100 Reisterstown Road", city: "Owings Mills", state: "MD", postalCode: "21117" },
  { id: "loc_nxn2qyg5", name: "Wegmans", address: "1413 S Main Chapel Way", city: "Gambrills", state: "MD", postalCode: "21054" },
  { id: "loc_gp7xemz7", name: "Wegmans", address: "1 Loop Road", city: "Auburn", state: "NY", postalCode: "13021" },
  { id: "loc_5zpv6n8n", name: "Wegmans", address: "500 South Meadow Street", city: "Ithaca", state: "NY", postalCode: "14850" },
  { id: "loc_v5yeg7nm", name: "Wegmans", address: "2000 Crossings Boulevard", city: "Lancaster", state: "PA", postalCode: "17601" },
  { id: "loc_xgwrkv76", name: "Wegmans", address: "3955 Route 31", city: "Liverpool", state: "NY", postalCode: "13090" },
  { id: "loc_mgwzvqpv", name: "Wegmans", address: "3325 West Genesee Street", city: "Syracuse", state: "NY", postalCode: "13219" },
  { id: "loc_kkye79qq", name: "Wegmans", address: "7519 Oswego Road", city: "Liverpool", state: "NY", postalCode: "13090" },
  { id: "loc_6jwq62x5", name: "Wegmans", address: "4722 Onondaga Boulevard", city: "Syracuse", state: "NY", postalCode: "13219" },
  { id: "loc_p7erppnk", name: "The Local Food Market LLC", address: "37 N. MAIN ST", city: "Cortland", state: "NY" },
  { id: "loc_rx8rn2jq", name: "Wegmans", address: "4979 W Taft Rd", city: "Liverpool", state: "NY", postalCode: "13088" },
  { id: "loc_z72e8yvw", name: "Wegmans", address: "4256 James Street", city: "East Syracuse", state: "NY", postalCode: "13057" },
  { id: "loc_5zpv6nmn", name: "Wegmans", address: "6789 East Genesee Street", city: "Fayetteville (DeWitt area)", state: "NY", postalCode: "13066" },
  { id: "loc_mgwzvqrv", name: "Wegmans", address: "650 Harry L Drive", city: "Johnson City", state: "NY", postalCode: "13790" },
  { id: "loc_8g2p9jx6", name: "Wegmans", address: "220 Highland Park Boulevard", city: "Wilkes-Barre Township", state: "PA", postalCode: "18702" },
  { id: "loc_p7erpw9k", name: "Wegmans", address: "1056 East Lancaster Avenue", city: "Downingtown", state: "PA", postalCode: "19335" },
  { id: "loc_6jwq6255", name: "Wegmans", address: "1315 Cold Spring Road", city: "Scranton", state: "PA", postalCode: "18508" },
  { id: "loc_jz8257me", name: "Wegmans", address: "371 Buckley Mill Road", city: "Wilmington", state: "DE", postalCode: "19807" },
  { id: "loc_9yenvg8y", name: "Wegmans", address: "100 Applied Bank Blvd", city: "Glen Mills", state: "PA", postalCode: "19342" },
  { id: "loc_xgwrkve6", name: "Wegmans", address: "3900 Tilghman Street", city: "Allentown", state: "PA", postalCode: "18104" },
  { id: "loc_nxn2qy65", name: "Wegmans", address: "50 Foundry Way", city: "Malvern", state: "PA", postalCode: "19355" },
  { id: "loc_ywnekqjv", name: "Wegmans", address: "600 Commerce Drive", city: "Collegeville", state: "PA", postalCode: "19426" },
  { id: "loc_wgpx592x", name: "Wegmans", address: "1 Village Drive", city: "King of Prussia", state: "PA", postalCode: "19406" },
  { id: "loc_5zpv6nxn", name: "Wegmans", address: "5000 Wegmans Drive", city: "Bethlehem", state: "PA", postalCode: "18017" },
  { id: "loc_mgwzvqkv", name: "Wegmans", address: "3791 Easton Nazareth Highway", city: "Easton", state: "PA", postalCode: "18045" },
  { id: "loc_2nvz6yg9", name: "Wegmans", address: "500 Montgomery Mall", city: "North Wales", state: "PA", postalCode: "19454" },
  { id: "loc_eqe8nk2v", name: "Wegmans", address: "1405 Main Street", city: "Warrington", state: "PA", postalCode: "18976" },
  { id: "loc_kkye79xq", name: "Wegmans", address: "2100 Route 70 West", city: "Cherry Hill", state: "NJ", postalCode: "08002" },
  { id: "loc_xgwrkkm6", name: "ShopRite Village - Washington", address: "2 Clubhouse Drive #31S", city: "Washington", state: "NJ" },
  { id: "loc_kkye775q", name: "Soulberry Natural Market - New Hope", address: "415 YORK ROAD #2", city: "New Hope", state: "PA" },
  { id: "loc_jz8255ke", name: "Basil Bandwagon Natural Market- 243 North Union", address: "239 north union street", city: "Lambertville", state: "NJ" },
  { id: "loc_8g2p9j86", name: "Wegmans", address: "2 Centerton Road", city: "Mount Laurel", state: "NJ", postalCode: "08054" },
  { id: "loc_2nvz66w9", name: "Basil Bandwagon - Clinton", address: "38 Old Hwy 22", city: "Clinton", state: "NJ" },
  { id: "loc_gp7xemj7", name: "Wegmans", address: "925 Vansant Dr", city: "Yardley", state: "PA", postalCode: "19067" },
  { id: "loc_2nvz6679", name: "ShopRite Village - Rio Grande", address: "1700 NJ-47 South", city: "Rio Grande", state: "NJ" },
  { id: "loc_eqe8nn9v", name: "Basil Bandwagon - Flemington", address: "276 US-202", city: "Flemington", state: "NJ" },
  { id: "loc_rx8rnnrq", name: "ShopRite Village - Chester", address: "195 U.S. Hwy 206 (Chester Mall)", city: "Chester", state: "NJ" },
  { id: "loc_9yenvg7y", name: "Wegmans", address: "240 Nassau Park Boulevard", city: "Princeton", state: "NJ", postalCode: "08540" },
  { id: "loc_z72e8ygw", name: "Wegmans", address: "724 Route 202 South", city: "Bridgewater", state: "NJ", postalCode: "08807" },
  { id: "loc_qxjrww2y", name: "ShopRite Village - Hammonton", address: "80 S Whitehorse Pike", city: "Hammonton", state: "NJ" },
  { id: "loc_wgpx55rx", name: "ShopRite Village - Marmora", address: "4 Roosevelt Blvd", city: "Marmora", state: "NJ" },
  { id: "loc_ywnekkmv", name: "ShopRite Village - Hillsborough", address: "601 Route 206", city: "Hillsborough", state: "NJ", postalCode: "08844" },
  { id: "loc_eqe8nngv", name: "ShopRite Village - Somers Point", address: "23 Bethel Road", city: "Somers Point", state: "NJ" },
  { id: "loc_kkye77eq", name: "ShopRite Village - Bernardsville", address: "93 Morristown Road", city: "Bernardsville", state: "NJ" },
  { id: "loc_jz82556e", name: "ShopRite Village - Somerset", address: "435 Elizabeth Ave", city: "Somerset", state: "NJ" },
  { id: "loc_7vny77pq", name: "ShopRite Village - Galloway", address: "401 S Pitney Rd", city: "Galloway", state: "NJ" },
  { id: "loc_5zpv66qn", name: "ShopRite Village - Stirling", address: "1153 Valley Road", city: "Stirling", state: "NJ" },
  { id: "loc_v5yeggkm", name: "ShopRite Village - Greater Morristown", address: "178 E Hanover Avenue", city: "Cedar Knolls", state: "NJ" },
  { id: "loc_qxjrwn6y", name: "Wegmans", address: "34 Sylvan Way", city: "Parsippany", state: "NJ", postalCode: "07054" },
  { id: "loc_6jwq66q5", name: "ShopRite Village - Chatham", address: "641 Shunpike Road", city: "Chatham", state: "NJ" },
  { id: "loc_nxn2qq95", name: "Food Bazaar - Piscataway", address: "581 Stelton Rd", city: "Piscataway", state: "NJ" },
  { id: "loc_z72e88mw", name: "ShopRite Village - Watchung", address: "1701 ROUTE 22 WEST", city: "Watchung", state: "NJ" },
  { id: "loc_gp7xee57", name: "ShopRite Village - Springfield", address: "727 Morris Turnpike", city: "Springfield", state: "NJ" },
  { id: "loc_9yenvv2y", name: "ShopRite Village - Garwood", address: "563 North Avenue East", city: "Garwood", state: "NJ" },
  { id: "loc_p7erpp5k", name: "ShopRite Village - Livingston", address: "483 S Livingston Avenue", city: "Livingston", state: "NJ" },
  { id: "loc_nxn2qq55", name: "ShopRite Village - Old Bridge", address: "600 Schulmeister Rd", city: "Old Bridge", state: "NJ" },
  { id: "loc_6jwq62z5", name: "Wegmans", address: "55 US Highway 9", city: "Manalapan", state: "NJ", postalCode: "Suite 100" },
  { id: "loc_mgwzvv5v", name: "ShopRite Village - Union", address: "2401D US Highway 22 W", city: "Union", state: "NJ" },
  { id: "loc_v5yeg72m", name: "Wegmans", address: "15 Woodbridge Center Drive", city: "Woodbridge", state: "NJ", postalCode: "07095" },
  { id: "loc_8g2p99p6", name: "ShopRite Village - Essex-Green", address: "1 Rooney Circle", city: "West Orange", state: "NJ" },
  { id: "loc_9yenvvwy", name: "Food Bazaar - Elizabeth", address: "BOGOPA - Elizabeth", city: "Elizabeth", state: "NJ" },
  { id: "loc_6jwq6695", name: "Food Bazaar - Carlstadt", address: "675 Paterson ave", city: "Carlstadt", state: "NJ" },
  { id: "loc_rx8rn2qq", name: "Wegmans", address: "100 Farm View", city: "Montvale", state: "NJ", postalCode: "07645" },
  { id: "loc_7vny7ezq", name: "Wegmans", address: "1104 Route 35", city: "Ocean Township", state: "NJ", postalCode: "07712" },
  { id: "loc_6jwq66y5", name: "Soulberry Natural Market - Spring Lake", address: "2407 NJ 71 SUITE #3", city: "Spring Lake", state: "NJ" },
  { id: "loc_6jwq66r5", name: "Key Food - 5th Ave", address: "4320 5th Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_7vny77wq", name: "Super Fresh - Bay Ridge Ave", address: "242 Bay Ridge Ave.", city: "Brooklyn", state: "NY" },
  { id: "loc_ywnekk7v", name: "The Health Nuts East Side Uptown 63rd and 2nd", address: "1208 2nd Avenue", city: "New York", state: "NY" },
  { id: "loc_mgwzvv8v", name: "Food Bazaar - Red Hook", address: "480 - 500 Van Brunt Street", city: "Brooklyn", state: "NY" },
  { id: "loc_rx8rnn5q", name: "Soulberry Natural Market - Hamilton", address: "1100 NJ-33", city: "Hamilton Square", state: "NJ" },
  { id: "loc_5zpv66en", name: "Food Bazaar - North Bergen", address: "1425 Kennedy Blvd North", city: "North Bergen", state: "NJ" },
  { id: "loc_z72e88nw", name: "Food Bazaar - West NY", address: "5701 Broadway", city: "West New York", state: "NJ" },
  { id: "loc_qxjrwwxy", name: "City Acres Market - Pine street", address: "70 Pine Street", city: "New York", state: "NY" },
  { id: "loc_wgpx55xx", name: "Mulberry Market NYC", address: "251 Mulberry Street", city: "New York", state: "NY" },
  { id: "loc_eqe8nnjv", name: "Westside Market NYC - 170 W 23rd", address: "170 W 23rd St", city: "New York", state: "NY" },
  { id: "loc_p7erppjk", name: "Gastro Market", address: "235 W 55th St", city: "New York", state: "NY" },
  { id: "loc_v5yeggqm", name: "Foodtown - Clinton St", address: "101 Clinton Street", city: "Brooklyn", state: "NY" },
  { id: "loc_v5yeggwm", name: "Food Bazaar - Fairview", address: "425 Anderson Avenue", city: "Fairview", state: "NJ" },
  { id: "loc_v5yeggrm", name: "Wegmans", address: "499 Lafayette Street", city: "New York", state: "NY", postalCode: "10003" },
  { id: "loc_2nvz6699", name: "Westerly Natural Market", address: "8th Avenue 911", city: "New York", state: "NY" },
  { id: "loc_rx8rnnxq", name: "DeCicco Family Markets - New City", address: "180 S. Main Street", city: "New City", state: "NY" },
  { id: "loc_8g2p99w6", name: "Sunac Natural Market", address: "600 W 42ND ST", city: "New York", state: "NY" },
  { id: "loc_9yenvv5y", name: "Dumbo Market - Smith St", address: "205 Smith St", city: "Brooklyn", state: "NY" },
  { id: "loc_mgwzvvyv", name: "Wholesome Farms Market Jay St", address: "108 Jay Street", city: "Brooklyn", state: "NY" },
  { id: "loc_mgwzvv6v", name: "Brooklyn Fare - Schermerhorn", address: "200 schermerhorn st", city: "Brooklyn", state: "NY" },
  { id: "loc_8g2p99y6", name: "Food Bazaar - Cropsey Ave", address: "2965 CROPSEY AVE", city: "Brooklyn", state: "NY" },
  { id: "loc_wgpx55yx", name: "Fairway Market - Upper West Side", address: "2131 Broadway", city: "New York", state: "NY" },
  { id: "loc_9yenvvyy", name: "Citarella - Upper West Side", address: "2135 Broadway", city: "New York", state: "NY" },
  { id: "loc_nxn2qq85", name: "LifeThyme Natural Market", address: "410 6th Ave", city: "New York", state: "NY" },
  { id: "loc_mgwzvvnv", name: "Lincoln Market - Greenwich Village", address: "501 6th Avenue", city: "New York", state: "NY" },
  { id: "loc_8g2p9j66", name: "Wegmans", address: "21 Flushing Avenue", city: "Brooklyn", state: "NY", postalCode: "11205" },
  { id: "loc_7vny77gq", name: "Dekalb Fresh Market", address: "825 DeKalb Avenue", city: "Brooklyn", state: "NY" },
  { id: "loc_qxjrwwzy", name: "Elly's Market", address: "230 Dekalb Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_eqe8nnwv", name: "Gracefully", address: "400 E 23rd St", city: "New York", state: "NY" },
  { id: "loc_p7erpprk", name: "Mr. Mango", address: "59 LAFAYETTE AVE", city: "Brooklyn", state: "NY" },
  { id: "loc_ywnekkev", name: "Mr. Lime Fruit & Vegetables", address: "313 7th Avenue", city: "Brooklyn", state: "NY" },
  { id: "loc_ywnekkzv", name: "Elm Wellness", address: "7th Avenue 56", city: "New York", state: "NY" },
  { id: "loc_nxn2qqk5", name: "Barzini", address: "2451 BROADWAY W 90TH ST", city: "New York", state: "NY" },
  { id: "loc_nxn2qq25", name: "Natural Frontier Market - Cortelyou Rd", address: "1102 Cortelyou Rd", city: "Brooklyn", state: "NY" },
  { id: "loc_ywnekk5v", name: "A Matter of Health NYC", address: "1347 1st Avenue", city: "New York", state: "NY" },
  { id: "loc_mgwzvvjv", name: "Ideal Food Basket", address: "720 Washington Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_rx8rnnpq", name: "Key Food - Fulton", address: "991 Fulton St", city: "Brooklyn", state: "NY" },
  { id: "loc_xgwrkkz6", name: "Lincoln Market - Lincoln Rd", address: "Lincoln Road 33", city: "Brooklyn", state: "NY" },
  { id: "loc_xgwrkkr6", name: "Ouri's Market", address: "427 Avenue U", city: "Brooklyn", state: "NY" },
  { id: "loc_z72e88qw", name: "Jubilee Marketplace", address: "145 west st", city: "Brooklyn", state: "NY" },
  { id: "loc_p7erppqk", name: "Fairway Market - Upper East Side", address: "240 East 86th St", city: "New York", state: "NY" },
  { id: "loc_7vny776q", name: "Food Garden Market - Franklin Ave", address: "608 FRANKLIN AVE", city: "Brooklyn", state: "NY" },
  { id: "loc_5zpv66jn", name: "Lincoln Market - Greenpoint", address: "1133 Manhattan Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_jz8255xe", name: "Lincoln Market - Flatbush", address: "210 Clarkson Avenue", city: "Brooklyn", state: "NY" },
  { id: "loc_qxjrwwgy", name: "KeyFood - Mcguinness Blvd", address: "224 McGuinness Boulevard", city: "Brooklyn", state: "NY" },
  { id: "loc_qxjrww7y", name: "The Food Emporium", address: "325 Lafayette Avenue", city: "Brooklyn", state: "NY" },
  { id: "loc_8g2p9956", name: "Food For Health", address: "1653 3rd Avenue", city: "New York", state: "NY", postalCode: "10128" },
  { id: "loc_6jwq66g5", name: "Market on Kent", address: "921 Manhattan Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_nxn2qqp5", name: "Urban Market by Key Food", address: "651 Nostrand Avenue", city: "Brooklyn", state: "NY" },
  { id: "loc_z72e88ew", name: "Rachel's garden", address: "116 Nassau Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_7vny77vq", name: "Citarella - Upper East Side", address: "1313 3rd Ave", city: "New York", state: "NY" },
  { id: "loc_jz82559e", name: "Westside Market NYC - 180 3rd Ave", address: "180 3rd Ave", city: "New York", state: "NY" },
  { id: "loc_z72e88rw", name: "Lincoln Market - Marcy Ave", address: "633 Marcy Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_gp7xeeq7", name: "Beyond Natural Market - Montrose Ave", address: "195 Montrose Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_jz8255we", name: "Food Bazaar - Manhattan Ave", address: "21 Manhattan Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_xgwrkk86", name: "C-town Graham", address: "330 GRAHAM AVE", city: "Brooklyn", state: "NY" },
  { id: "loc_wgpx55kx", name: "Lemon Tree Food Market", address: "387 Graham Avenue", city: "Brooklyn", state: "NY" },
  { id: "loc_rx8rnneq", name: "Met Fresh of Bed-Stuy", address: "410 Tompkins Avenue", city: "Brooklyn", state: "NY" },
  { id: "loc_gp7xee27", name: "Food Bazaar - AFS / Myrtle", address: "1102 Myrtle Avenue", city: "Brooklyn", state: "NY" },
  { id: "loc_wgpx55nx", name: "Food Bazaar - Harlem", address: "201 E 125th St", city: "New York", state: "NY" },
  { id: "loc_qxjrwwyy", name: "Food Bazaar - Flatbush", address: "1009 FLATBUSH AVE", city: "Brooklyn", state: "NY" },
  { id: "loc_9yenvvmy", name: "FOOD UNIVERSE #2628 - FLATBUSH AVE", address: "369 Flatbush Avenue", city: "Brooklyn", state: "NY" },
  { id: "loc_qxjrwwky", name: "Foodtown - Noll St", address: "54 A Noll Street", city: "Brooklyn", state: "NY" },
  { id: "loc_z72e88zw", name: "Food Bazaar - Bronx Exterior St", address: "610 Exterior St 4th FLOOR", city: "Bronx", state: "NY" },
  { id: "loc_ywnekkwv", name: "City Fresh Market - Astoria", address: "2115 Broadway", city: "Astoria", state: "NY" },
  { id: "loc_p7erppkk", name: "Knickerbocker Fresh Market", address: "341 Knickerbocker Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_2nvz66r9", name: "Food Bazaar - LIC", address: "4202 Northen Blvd.", city: "Long Island City", state: "NY" },
  { id: "loc_xgwrkk26", name: "Food Bazaar - St. John Place", address: "1682 St. John's Place", city: "Brooklyn", state: "NY" },
  { id: "loc_2nvz6659", name: "LILY FRUIT & VEGETABLES", address: "1932 Fulton St", city: "Brooklyn", state: "NY" },
  { id: "loc_gp7xee87", name: "Lincoln Market - Fulton St", address: "1134 FULTON ST", city: "Brooklyn", state: "NY" },
  { id: "loc_rx8rnnkq", name: "Food Bazaar - Concourse", address: "238 E. 161th Street", city: "Bronx", state: "NY" },
  { id: "loc_kkye77jq", name: "Key Food - 30th Ave", address: "42-15 30th Ave", city: "Astoria", state: "NY" },
  { id: "loc_6jwq66e5", name: "Food Bazaar - Wyckoff", address: "17-59 Ridgewood PL.", city: "Brooklyn", state: "NY" },
  { id: "loc_xgwrkkp6", name: "Food Bazaar - Bronx 445 East", address: "445 East 163rd St", city: "Bronx", state: "NY" },
  { id: "loc_p7erpp8k", name: "Food Bazaar - Gates", address: "1580 Gates Ave", city: "Ridgewood", state: "NY" },
  { id: "loc_eqe8nnzv", name: "Lincoln Market - Astoria", address: "21-27 31st St", city: "Astoria", state: "NY" },
  { id: "loc_p7erppxk", name: "Adams Fairacre Farms - Wappinger", address: "160 Old Post Road", city: "Wappinger", state: "NY" },
  { id: "loc_2nvz66m9", name: "Food Bazaar - 170th", address: "535 East 170th Street", city: "Bronx", state: "NY" },
  { id: "loc_7vny775q", name: "Food Bazaar - Douglaston", address: "242-02 61st Street", city: "Little Neck", state: "NY" },
  { id: "loc_gp7xee67", name: "Westside Market NYC - 2589 Broadway", address: "2589 Broadway", city: "New York", state: "NY" },
  { id: "loc_2nvz66x9", name: "Gourmet Garage - Tribeca", address: "366 Broadway", city: "New York", state: "NY" },
  { id: "loc_ywnekk8v", name: "Food Bazaar - Flatlands", address: "11110 Flatlands Ave", city: "Brooklyn", state: "NY" },
  { id: "loc_rx8rnngq", name: "Food Bazaar -35-60 Junction Blvd", address: "35-60 Junction Blvd", city: "Corona", state: "NY" },
  { id: "loc_jz8255ye", name: "Food Bazaar - 58-01 Junction Blvd", address: "58-01 Junction Blvd.", city: "Elmhurst", state: "NY" },
  { id: "loc_eqe8nnxv", name: "Food Bazaar - 57th Ave", address: "97-27 57th Avenue", city: "Corona", state: "NY" },
  { id: "loc_eqe8nn6v", name: "Food Bazaar - Linden", address: "2784 LINDEN BLVD", city: "Brooklyn", state: "NY" },
  { id: "loc_5zpv66zn", name: "DeCicco & Sons - Ardsley", address: "21 center street", city: "Ardsley", state: "NY" },
  { id: "loc_gp7xee97", name: "Food Bazaar - Mt. Vernon", address: "One Bogopa Plaza", city: "Mt Vernon", state: "NY" },
  { id: "loc_6jwq66j5", name: "DeCicco Family Markets - Jefferson Valley", address: "3651 Lee Road", city: "Jefferson Valley", state: "NY" },
  { id: "loc_jz8255ze", name: "DeCicco & Sons - Pelham", address: "43 Fifth Avenue", city: "Pelham", state: "NY" },
  { id: "loc_v5yegg5m", name: "Citarella - West Village", address: "424 6th Ave", city: "New York", state: "NY" },
  { id: "loc_nxn2qqx5", name: "DeCicco & Sons - Eastchester", address: "777 WHITE PLAINS RD", city: "Scarsdale", state: "NY" },
  { id: "loc_eqe8nnqv", name: "DeCicco & Sons - Millwood", address: "230 Saw Mill River Road", city: "Millwood", state: "NY" },
  { id: "loc_z72e887w", name: "DeCicco & Sons - Larchmont", address: "2141 Palmer Ave", city: "Larchmont", state: "NY" },
  { id: "loc_kkye776q", name: "Food Bazaar - Cambria Heights", address: "217-20 LINDEN BLVD", city: "Cambria Heights", state: "NY" },
  { id: "loc_jz8255ge", name: "Healthy Living - Saratoga Springs/Wilton", address: "3065 NY Rt 50", city: "Saratoga Springs", state: "NY" },
  { id: "loc_gp7xeep7", name: "DeCicco & Sons - Sleepy Hollow", address: "1 LEGEND DRIVE", city: "Sleepy Hollow", state: "NY" },
  { id: "loc_8g2p99z6", name: "Metro Acres Market", address: "175 Clinton Street", city: "New York", state: "NY" },
  { id: "loc_2nvz66n9", name: "DeCicco & Sons - Harrison", address: "7 Halstead Avenue", city: "Harrison", state: "NY" },
  { id: "loc_gp7xeex7", name: "North Shore Farms - Great Neck", address: "90 Horace Harding Blvd", city: "Great Neck", state: "NY" },
  { id: "loc_7vny77qq", name: "Wegmans", address: "106 Corporate Park Drive", city: "West Harrison", state: "NY", postalCode: "10604" },
  { id: "loc_mgwzvvgv", name: "DeCicco & Sons - Armonk", address: "17 Maple Ave", city: "Armonk", state: "NY" },
  { id: "loc_9yenvv6y", name: "KeyFood - Long Beach", address: "1080 W Beech St", city: "Long Beach", state: "NY" },
  { id: "loc_5zpv669n", name: "Brooklyn Fare - Cherry St", address: "227 Cherry Street", city: "New York", state: "NY" },
  { id: "loc_kkye77kq", name: "DeCicco & Sons - Somers", address: "266 Route 202", city: "Somers", state: "NY" },
  { id: "loc_8g2p99m6", name: "KeyFood - 151 Covert Ave", address: "151 COVERT AVENUE", city: "Floral Park", state: "NY" },
  { id: "loc_5zpv66yn", name: "Westside Market NYC - 77 7th Ave", address: "77 7th Ave", city: "New York", state: "NY" },
  { id: "loc_8g2p99g6", name: "DeCicco Family Markets- Katonah", address: "132 Bedford Road", city: "Katonah", state: "NY" },
  { id: "loc_ywnekk2v", name: "KeyFood - Ocean Ave", address: "399 Ocean Ave.", city: "Rockville Centre", state: "NY" },
  { id: "loc_v5yeggzm", name: "KeyFood - Long Beach Park Ave", address: "663 E Park Ave", city: "Long Beach", state: "NY" },
  { id: "loc_wgpx55gx", name: "DeCicco & Sons - Bedform", address: "422 Old Post Road", city: "Bedford", state: "NY" },
  { id: "loc_jz82552e", name: "North Shore Farms - Glen Cove", address: "190 Glen Cove Avenue", city: "Glen Cove", state: "NY" },
  { id: "loc_rx8rnnvq", name: "Citarella - Greenwich", address: "600 West Putnam Avenue", city: "Greenwich", state: "CT" },
  { id: "loc_xgwrkkg6", name: "DeCicco & Sons - Brewster", address: "50 independent Way", city: "Brewster", state: "NY" },
  { id: "loc_mgwzvvzv", name: "North Shore Farms - Mineola", address: "330 E. Jericho Turnpike", city: "Mineola", state: "NY" },
  { id: "loc_nxn2qqz5", name: "Food Bazaar - Hempstead", address: "132 FULTON AVE", city: "Hempstead", state: "NY" },
  { id: "loc_9yenvvjy", name: "Super Fresh - Grand Ave", address: "1764 Grand Avenue", city: "Baldwin", state: "NY" },
  { id: "loc_kkye77zq", name: "Food Bazaar - Westbury", address: "1258 Corporate Drive", city: "Westbury", state: "NY" },
  { id: "loc_9yenvvpy", name: "Wegmans", address: "675 Connecticut Avenue", city: "Norwalk", state: "CT", postalCode: "06851" },
  { id: "loc_7vny77jq", name: "KeyFood - Carmans Rd", address: "941 Carmans Road", city: "Massapequa", state: "NY" },
  { id: "loc_z72e88xw", name: "Chamomille Natural Foods Inc", address: "58 Newtown Rd", city: "Danbury", state: "CT" },
  { id: "loc_eqe8nn8v", name: "North Shore Farms - Commack", address: "40 Vanderbilt Parkway", city: "Commack", state: "NY" },
  { id: "loc_2nvz66z9", name: "New Morning Country Store LLC", address: "129 Main St N", city: "Woodbury", state: "CT" },
  { id: "loc_5zpv66vn", name: "North Shore Farms - Hauppauge", address: "1235 VETS HIGHWAY", city: "Hauppauge", state: "NY" },
  { id: "loc_5zpv667n", name: "Food Bazaar - Bridgeport", address: "500 Sylvan Avenue", city: "Bridgeport", state: "CT" },
  { id: "loc_gp7xeeg7", name: "Healthy Living - South Burlington", address: "222 DORSET ST", city: "South Burlington", state: "VT" },
  { id: "loc_mgwzvv7v", name: "Food Bazaar - Bridgeport", address: "345 Huntington Turnpike", city: "Bridgeport", state: "CT" },
  { id: "loc_5zpv66rn", name: "Healthy Living - Williston", address: "129 Market Street", city: "Williston", state: "VT" },
  { id: "loc_v5yeggmm", name: "Edge of the Woods Market", address: "379 Whalley Avenue", city: "New Haven", state: "CT" },
  { id: "loc_wgpx557x", name: "Good Nature Cafe Inc - Broadway", address: "15 Broadway", city: "New Haven", state: "CT" },
  { id: "loc_nxn2qqj5", name: "Good Nature Café Inc - Whitney", address: "44 Whitney Ave", city: "New Haven", state: "CT" },
  { id: "loc_wgpx55mx", name: "ATTICUS MARKET", address: "771 ORANGE ST", city: "New Haven", state: "CT" },
  { id: "loc_wgpx55wx", name: "Thyme & Season", address: "3040 Whitney Avenue", city: "Hamden", state: "CT" },
  { id: "loc_v5yeggpm", name: "Tangiers International Market", address: "550 FARMINGTON AVE", city: "Hartford", state: "CT" },
  { id: "loc_ywnekkvv", name: "Foodworks - Guilford", address: "450 Boston Post Road", city: "Guilford", state: "CT" },
  { id: "loc_8g2p99q6", name: "Citarella - Southampton", address: "20 Hampton Rd", city: "Southampton", state: "NY" },
  { id: "loc_kkye778q", name: "Citarella - Bridgehampton", address: "2209 Montauk Hwy", city: "Bridgehampton", state: "NY" },
  { id: "loc_6jwq66v5", name: "Citarella - East Hampton", address: "2 Pantigo Rd", city: "East Hampton", state: "NY" },
  { id: "loc_gp7xemk7", name: "Wegmans", address: "9102 Shops Way", city: "Northborough", state: "MA", postalCode: "01532" },
  { id: "loc_p7erpp7k", name: "Clements Marketplace", address: "1150 HOPE STREET", city: "Bristol", state: "RI" },
  { id: "loc_5zpv6ngn", name: "Wegmans", address: "53 Third Avenue", city: "Burlington", state: "MA", postalCode: "01803" },
  { id: "loc_mgwzvqev", name: "Wegmans", address: "200 Boylston Street", city: "Chestnut Hill", state: "MA", postalCode: "02467" },
  { id: "loc_jz8257qe", name: "Wegmans", address: "169 University Avenue", city: "Westwood", state: "MA", postalCode: "02090" },
  { id: "loc_xgwrkv56", name: "Wegmans", address: "3850 Mystic Valley Parkway", city: "Medford", state: "MA", postalCode: "02155" },
  { id: "loc_xgwrkk96", name: "John Edward's Market Inc.", address: "158 Main St", city: "Ellsworth", state: "ME" },
];
